### ISSUE TITLE
Fix markup on BF page.

### ISSUE THREAD

**Issue by jelkner** [Jakob-Ayers/website#4]
Check the validation errors on your [BF page](https://jakob-ayers.github.io/website/bf.html).  You need to use &lt; and &gt; to render angle brackets in HTML.

**Comment by jelkner** [comment]
Same issue on [this](https://jakob-ayers.github.io/website/eloquent-javascript/chapter-1.html) page.

**Comment by Jakob-Ayers** [comment]
now validates 👍
