### ISSUE TITLE
Don't forget to link all your work from your homepage

### ISSUE THREAD

**Issue by jelkner** [Jakob-Ayers/website#5]
Your [holiday project](https://jakob-ayers.github.io/website/experiments/navidad.html) should be linked from your homepage (see step-by-step instructions on [week 13](https://ict.gctaa.net/sections/webdesign/goals/week13.html).  The file should be renamed to ``index.html`` also.

**Comment by Jakob-Ayers** [comment]
It has been renamed and linked
